name: Go Coverage Badge
description: Generate coverage badge for go projects
author: dannysy
inputs:
  coveragePath:
    description: 'path to file with coverage test report'
    required: true
    default: coverage.out
  readmePath:
    description: 'path to README.md'
    required: false
    default: README.md


runs:
  using: 'composite'
  steps:
    - name: Checkout Current Repository
      uses: actions/checkout@v3
      with:
        repository: dannysy/go-badges
        path: ./go-badges/
    - name: Update Coverage Badge in README.md
      run: cd ./go-badges/ &&
        echo "GO111MODULE=on" && 
        ls -a &&
        cat ${{inputs.coveragePath} &&
        go build -o runnable ./main.go &&
        cd .. &&
        ./go-badges/runnable cb -cf=${{inputs.coveragePath}} -rf=${{inputs.readmePath}}
      shell: bash
branding:
  icon: check
  color: blue