name: Go Coverage Badge
description: Generate coverage badge for go projects
author: dannysy
inputs:
  coveragePath:
    description: 'path to file with coverage test report'
    required: true
    default: coverage.out
  readmePath:
    description: 'path to README.md'
    required: false
    default: README.md


runs:
  using: 'composite'
  steps:
    - run: go run main.go cb -cf=${{coveragePath}} -rf=${{readmePath}}
      shell: bash
branding:
  icon: check
  color: blue